name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests and check coverage
        run: ./gradlew check

      - name: Run tests and generate JaCoCo report
        run: ./gradlew test jacocoTestReport

      - name: Send Slack notification if coverage failed
        if: failure()  # This triggers only if a previous step failed
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"🚨 *Code coverage failed* in build #${{ github.run_number }} for branch *${{ github.ref_name }}*\"
          }" $SLACK_WEBHOOK_URL