name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests and check coverage
        run: ./gradlew check

      - name: Run tests and generate JaCoCo report
        run: ./gradlew test jacocoTestReport

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()  # Ensures this runs whether build succeeds or fails

    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "${{ needs.build.result }}" == "success" ]; then
            STATUS="✅ Build succeeded"
            COLOR="#36a64f"
          else
            STATUS="❌ Build failed"
            COLOR="#ff0000"
          fi

          curl -X POST -H 'Content-type: application/json' --data "{
            \"attachments\": [{
              \"fallback\": \"$STATUS\",
              \"color\": \"$COLOR\",
              \"title\": \"$STATUS\",
              \"text\": \"Build #${{ github.run_number }} on branch *${{ github.ref_name }}*.\",
              \"footer\": \"GitHub Actions\",
              \"ts\": $(date +%s)
            }]
          }" $SLACK_WEBHOOK_URL
